### ISSUE TITLE
not working for me on python 3

### ISSUE THREAD

**Issue by faheem-khaskheli** [TongRuizheWithGzz/videoavatars-py3#1]

**Comment by faheem-khaskheli** [comment]
2021-07-07 16:59:55,738 [step1_pose.py:main:291] Initial fit
2.05e+03 | init_pose_1: 2.05e+03
Traceback (most recent call last):
  File "step1_pose.py", line 377, in <module>
    args.body_height, args.nohands, args.display)
  File "step1_pose.py", line 300, in main
    init(init_frames, body_height, b2m, debug_rn)
  File "step1_pose.py", line 93, in init
    callback=get_cb(viz_rn, f)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/optimization.py", line 41, in minimize
    return minimize_dogleg(fun, free_variables=x0, on_step=callback, **options)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/optimization_internal.py", line 409, in minimize_dogleg
    state.updateJ(obj)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/optimization_internal.py", line 305, in updateJ
    self.J = obj.J
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/optimization_internal.py", line 106, in J
    result = self.dr_wrt(self.x, profiler=self.profiler).copy()
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/optimization_internal.py", line 51, in dr_wrt
    new_jac = self.obj.dr_wrt(freevar, profiler=profiler)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/ch.py", line 772, in dr_wrt
    dr2 = p.dr_wrt(wrt, profiler=profiler)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/ch.py", line 772, in dr_wrt
    dr2 = p.dr_wrt(wrt, profiler=profiler)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/ch.py", line 772, in dr_wrt
    dr2 = p.dr_wrt(wrt, profiler=profiler)
  [Previous line repeated 2 more times]
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/ch.py", line 775, in dr_wrt
    indirect_dr = self.compute_rop(p, rhs=dr2)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/ch.py", line 724, in compute_rop
    dr = self._compute_dr_wrt_sliced(wrt)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/chumpy/ch.py", line 289, in _compute_dr_wrt_sliced
    result = self.compute_dr_wrt(wrt)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/opendr/camera.py", line 104, in compute_dr_wrt
    result = sp.csc_matrix((data, (IS, JS)))
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 51, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/scipy/sparse/coo.py", line 150, in __init__
    self._shape = check_shape((M, N))
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/scipy/sparse/sputils.py", line 281, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File "/mnt/2210956D109548A5/user/videoavatars/.venv/lib/python3.7/site-packages/scipy/sparse/sputils.py", line 281, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
